patricia: patricia_tool.c patricia_parallel.c patricia_test.c
	gcc -static patricia_tool.c patricia_parallel.c patricia_test.c -O3 -o patricia_parallel -lpthread

clean:
	rm -rf patricia_parallel output*
